{{- if .Values.secret.appSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: nexvion-secret
  namespace: nexvion-helm
type: Opaque
stringData:
  APP_SECRET: {{ .Values.secret.appSecret | quote }}
{{- end }}
